#from bs4 import BeautifulSoup as bs
import requests
import pandas
import pdb
# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

b = 0
link = []
model = ""

def test_cenemodela(self, link):
    tarifa = ""
    model = link[41:link.find("?")]
    selektor = "#tariffTab-{} > .a-01-text__secondary--base"
    cena_slajder = "#tariffSlider-{} > .o-content-slider__card-wrapper:nth-child({}) .a-01-text__secondary-bold--lg"
    tarifa_slajder = "#tariffSlider-{} > .o-content-slider__card-wrapper:nth-child({}) .a-01-text__secondary-bold--2xl"
    cena_telefona = {}
    self.get(link)
    time.sleep(0.4)
    self.find_element(By.CSS_SELECTOR, ".basket-tariff-label-desktop").click()
    time.sleep(0.5)
    self.find_element(By.CSS_SELECTOR, ".js-modal-trigger > .a-02-button__label").click()
    for x in range(17,0,-1):
        try:
            self.find_element(By.CSS_SELECTOR, selektor.format(x)).click()
            for y in range(1,3):
                if x == 5: 
                    popust = 1 
                else:
                    popust = 0.9
                tarifa = self.find_element(By.CSS_SELECTOR, tarifa_slajder.format(x,y)).text
                cena_telefona[tarifa] = int(int(self.find_element(By.CSS_SELECTOR, cena_slajder.format(x,y)).text.replace(" RSD", "").replace(".","")) / popust)
        except:
            continue
#    print(model, cena_telefona, "\n", sep=" ---- ")
    return(cena_telefona)


###
###         Kreiranje elementa WebDriver
###
Vip_Sajt = webdriver.Chrome("E:\Temp\chromedriver.exe")                 

###
###         Otvaranje stranice
###
Vip_Sajt.get("https://www.vipmobile.rs/privatni/uredjaji/telefoni")      

###
###         Moram naći element kom se može dodeliti tipka END
###
for a in range(1,4):
    Vip_Sajt.find_element_by_id("privatni").send_keys(Keys.END)             
    time.sleep(2)

element = Vip_Sajt.find_element_by_id("devices_list")
try:
    for a in Vip_Sajt.find_element_by_id("devices_list").find_elements_by_xpath(".//a"):
        link.append(a.get_attribute('href'))
except:
    print("\n")

link.sort()
for index, a in enumerate(link):
    print(index, a, sep=" - ")
for a in link:
    if "device" in a:
        cene = test_cenemodela(Vip_Sajt, a)
breakpoint()
Vip_Sajt.close()
